### ISSUE TITLE
Channels Updates

### ISSUE THREAD

**Issue by maddox** [Protektor-Desura/Archon#2]
Heya, thanks for including Channels in the media server comparison list!

I read through it and saw some things that are a bit out of date and I thought I'd include them. Since I can't fork the wiki and update them myself and contribute it, I just made this issue.

Thanks!

## Features

- ✅ [Music Video Support](https://getchannels.com/2022/03/23/video-imports/)
- ✅ [Mobile Sync](https://getchannels.com/2022/04/12/offline-downloads/)
- ✅ [Favorites and Tags](https://getchannels.com/docs/apps/usage/favorites/)
- ✅ [Collections](https://getchannels.com/library-collections/)
- ✅ [Remote Login Server](https://getchannels.com/docs/articles/how-to/stream-remotely/)
- ✅ [Recommend & Discover](https://getchannels.com/on-later/)

## Server OS

- ✅ [Nvidia Shield](https://getchannels.com/dvr-server/#nvidiashield)

## Plugins

These video sources can be added to Channels via our [Custom Channels](https://getchannels.com/custom-channels/) feature. Here's links to community threads describing the projects that do it.

[Here's a category on our Community](https://community.getchannels.com/c/playground/custom-channels/36) that describes all the different ways you can use Custom Channels

- ✅ [Pluto TV](https://community.getchannels.com/t/pluto-for-channels/24870) - [Easier Way](https://community.getchannels.com/t/non-docker-source-for-plutotv-and-stirr-m3u-playlists-and-epg/29308)
- ✅ [Stirr TV](https://community.getchannels.com/t/stirr-for-channels/27140) - - [Easier Way](https://community.getchannels.com/t/non-docker-source-for-plutotv-and-stirr-m3u-playlists-and-epg/29308)
- ✅ TMDB - Movies in Channels DVR Server are scraped with TMDB.

## Clients

- ✅ [Kodi](https://community.getchannels.com/t/kodi-add-on/9478/466)
- ✅ Web browser - the web admin serves as a client as you can watch anything from it

**Comment by Protektor-Desura** [comment]
The chart has been updated. Let me know if there are any other updates or wrong information.
