### ISSUE TITLE
Plex Removes Podcast Support

### ISSUE THREAD

**Issue by GenusGeoff** [Protektor-Desura/Archon#5]
In the latest Plex updates from this Spring, Plex abandoned support for podcasts and web videos.

[News Source 1](https://www.upi.com/Top_News/US/2022/04/12/plex-remove-podcast-web-shows-friday-not-worth-our-time/1031649775957/)

[Plex Forum Statement](https://forums.plex.tv/t/podcasts-and-web-shows-are-going-away-on-april-15-2022/787096)

**Comment by Protektor-Desura** [comment]
I have updated the chart with this info. Thanks
